config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tasks
  resource :session, :only => [:new, :create, :destroy]
  get '/login' => "sessions#new", :as => "login"
  get '/logout' => "sessions#destroy", :as => "logout"
  
  get '/forgot_password' => "users#forgot_password", :as => "forgot"
  post 'reset_password' => "users#reset_password", :as => "reset"
  get '/change_password' => "users#change_password", :as => "change_pass"
  post 'commit_change_password' => "users#commit_change_password", :as => "commit_change_pass"
  post 'delete_multiple_tasks' => "tasks#destroy_multiple", :as => "destroy_multiple"

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
	validates :title, :description, presence: true
	validates :title, length: { :in => 4..100 }
	validates :description, length: { :in => 4..500 }
	validates :title, :description, :format => {:with => /\w+\s*\d*/, :message => "This field can contain only letters spaces and numbers." }
	self.per_page = 5
	belongs_to :user
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate
  # GET /tasks
  # GET /tasks.json
  def index
    @user = current_user
    @tasks = Task.where(:user_id => @user.id).paginate(:page => params[:page])
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @user = current_user
    @task.user_id = @user.id
    @task.created_date = Time.new
    respond_to do |format|
      if @task.save
        #format.html { redirect_to @task, notice: 'Task was successfully created.' }
       # format.json { render :show, status: :created, location: @task }
	format.js
      else
        #format.html { render :new }
        format.json { render json: @task.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
	format.js
      else
        format.html { render :edit }
        format.json { render json: @task.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def destroy_multiple
	if params[:delete]
  		params[:delete].each do |id|
			Task.find(id[0].to_i).destroy
		end
	end
	redirect_to tasks_url, notice: 'Tasks were successfully destroyed.'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_dialog.html.erb
	
<div class="modal fade"
           id="dialog" tabindex="-1" role="dialog" 
           aria-labelledby="myModalLabel"
           aria-hidden="true" 
           data-backdrop="static" 
           data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" 
                data-dismiss="modal" 
                aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>
     
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/tasks/_form.html.erb
<%= form_for(@task, remote: true, :html => { :role => "form"}) do |f| %>
<div id="error_explanation" class="bg-danger text-danger">
</div>
  

  <div class="form-group">
    <%= f.label :title, class: 'control-label' %><br>
    <%= f.text_field :title, class: 'form-control' %>
    <span class="help-block"></span>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'control-label' %><br>
    <%= f.text_area :description, class: 'form-control' %>
    <span class="help-block"></span>
  </div>
  <div class="actions">
    <%= f.submit @task.new_record? ? 'Create' : 'Update', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/tasks/_show.html.erb
<div class="row">
<div class="col-sm-4">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Created date:</strong>
  <%= @task.created_date %>
</p>
</div>
</div>

app/views/tasks/_task.html.erb
<tr id="task<%= task.id %>">
	<td><%= check_box_tag("delete[#{task.id}]") %></td>
        <td><%= task.title %></td>
        <td><%= task.created_date %></td>
        <td><%= link_to 'Show', task, remote: true, :class => 'btn btn-sm btn-success' %></td>
        <td><%= link_to 'Edit', edit_task_path(task), remote: true, :class => 'btn btn-sm btn-info' %></td>
        <td><%= link_to 'Delete', task, remote: true, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger' %></td>
      </tr>

app/views/tasks/create.js.erb
$('#dialog').modal('toggle');
$('#tasks').append('<%= j render (@task) %>')
window.location.reload(true);

app/views/tasks/destroy.js.erb
$('#task<%= @task.id %>').fadeOut();
window.location.reload(true);

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
	
// Add the dialog title
$('#dialog h3').html("<i class=' glyphicon glyphicon-pencil'></i> Edit Task");
 
// Render the edit form
$('.modal-body').html('<%= j render("form") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");
 
// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

app/views/tasks/index.html.erb
<h1>Your Tasks</h1>
<%= form_tag destroy_multiple_path do %>
<table class="table-bordered" style="width: 100%; text-align: center">
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>Title</th>
      <th>Created date</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody id ="tasks">
    <%= render @tasks %>
  </tbody>

</table>
<div class="actions">
		<%= submit_tag 'Remove selected',  class: 'btn btn-default' %>
</div>
<% end %>
<div style="text-align: center">
	<%= will_paginate @tasks, renderer: BootstrapPagination::Rails, :is_active => true %>
</div>
<%= render 'dialog' %>
<br>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
	
// Add the dialog title
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> Add New Task");
 
// Render the new form
$('.modal-body').html('<%= j render("form") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");
 
// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

app/views/tasks/show.js.erb
// Add the dialog title
$('#dialog h3').html("<i class=' glyphicon glyphicon-pencil'></i> Details");
 
// Render the edit form
$('.modal-body').html('<%= j render("show") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");

app/views/tasks/update.js.erb
$('#dialog').modal('toggle');
$('#task<%= @task.id %>').replaceWith('<%= j render (@task) %>')