config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tasks
  resource :session, :only => [:new, :create, :destroy]
  get '/login' => "sessions#new", :as => "login"
  get '/logout' => "sessions#destroy", :as => "logout"
  
  get '/forgot_password' => "users#forgot_password", :as => "forgot"
  post 'reset_password' => "users#reset_password", :as => "reset"
  get '/change_password' => "users#change_password", :as => "change_pass"
  post 'commit_change_password' => "users#commit_change_password", :as => "commit_change_pass"
  post 'delete_multiple_tasks' => "tasks#destroy_multiple", :as => "destroy_multiple"

  root 'tasks#index'

end

app/models/user.rb
require 'digest'
require 'securerandom'
class User < ActiveRecord::Base
	attr_accessor :password
	
	has_many :tasks
	
	validates_uniqueness_of :email, :login
	validates_length_of :email, :within => 5..50
	validates :email, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
	validates_confirmation_of :password
	validates_length_of :password, :within => 4..20
	validates_presence_of :password, :if => :password_required?
	
	before_save :encrypt_new_password
	before_create { generate_token(:auth_token) }
	def self.authenticate(email, password)
		user = find_by_email(email)
		return user if user && user.authenticated?(password)
	end
	
	def authenticated?(password)
		self.hashed_password == encrypt(password)
	end
	
	protected
	def encrypt(string)
		Digest::SHA1.hexdigest(string)
	end	

	def encrypt_new_password
		return if password.blank?
		self.hashed_password = encrypt(password)
	end
	
	def password_required?
		hashed_password.blank? || password.present?
	end
	
	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])
	end
	
end

app/controllers/users_controller.rb
require 'securerandom'
require 'digest'
class UsersController < ApplicationController
	before_action :check_email_and_user, only: [:reset_password]
	before_action :check_passwords, only: [:commit_change_password]
	before_action :authenticate, except: [:new, :create, :forgot_password, :reset_password]
	
	def index
		@users = User.all
	end
	def show
	end
	
	def new
		if !logged_in?
			@user = User.new
		else
			redirect_to root_path, :notice => "You have already an account"
		end
	end
	
	def edit
		@user = current_user
		if @user == nil
			redirect_to root_path, :notice => "logged"
		end
	end

	def create
		if !logged_in?
			@user = User.new(user_params)
			respond_to do |format|
				if @user.save
					UserMailer.welcome_email(@user).deliver_now!
					format.html { redirect_to login_path, notice: 'User was succesdljfk'}
					format.json { render :show, status: :created, location: @user }
				else
					format.html { render :new }
					format.json { render json: @user.errors, status: :unprocessable_entity }
				end
			end
		end
	end
	
	def update
		@user = current_user
		respond_to do |format|
			if @user.update(user_params)
				format.html { redirect_to @user, notice: 'User was succesdljfk'}
				format.json { render :show, status: :ok, location: @user }
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@user = current_user
		Task.where(:user_id => @user.id).destroy_all
		@user.destroy
		redirect_to logout_path, :notice => "Your account has been removed."
		
	end
	def forgot_password
	end
	
	def reset_password
	end
	
	def change_password
	end

	def commit_change_password
		if (params[:new_password] != params[:password_confirmation]) 
			redirect_to change_pass_path, :notice => "Passwords don't match"
		elsif  !(params[:new_password].length.between?(4,20))
			redirect_to change_pass_path, :notice => "Passwords must have at least 4 signs and less than 20"
		else
			@user = current_user
			if Digest::SHA1.hexdigest(params[:old_password]) == @user.hashed_password
				@user.update_attribute(:hashed_password, Digest::SHA1.hexdigest(params[:new_password]))
				redirect_to tasks_path, :notice => "Your password has been changed."
			else
				redirect_to change_pass_path, :notice => "Old password is incorrect"
			end
		end
	end

	private
	def set_user
		@user = User.find(params[:id])
	end
	
	def check_passwords
		
	end
	
	def check_email_and_user
		if /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/.match(params[:email])
			@user = User.find_by_email(params[:email])
			if @user == nil
				redirect_to forgot_path, :notice => "There is no user in database with given email"
			else
				newpass = SecureRandom.urlsafe_base64(15)
				@user.hashed_password = newpass
				UserMailer.reset_password_mail(@user).deliver_now!
				@user.update_attribute(:hashed_password, Digest::SHA1.hexdigest(newpass))
				redirect_to login_path, :notice => "Your password has been changed. Please check your email inbox"
			end
		else
			redirect_to forgot_path, :notice => "Invalid email address"
		end
	end

	def user_params
		params.require(:user).permit(:email, :login, :password, :password_confirmation)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
<div class="col-sm-4">
<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
		<div class="alert alert-danger">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
			<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="form-group">
		<%= f.label :login, class: 'control-label' %><br />
		<%= f.text_field :login, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :email, class: 'control-label' %><br />
		<%= f.text_field :email, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :password, class: 'control-label' %><br />
		<%= f.password_field :password, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :password_confirmation, class: 'control-label' %><br />
		<%= f.password_field :password_confirmation, class: 'form-control' %>
	</div>
	<div class="actions">
		<%= f.submit 'Register', class: 'btn btn-default' %>
	</div>
<% end %>
</div>
</div>

app/views/users/change_password.html.erb
<h1>Change password</h1>
<div class="row">
<div class="col-sm-4">
<%= form_tag commit_change_pass_path do %>
	<div class="form-group">
		<%= label_tag 'Enter your old password',nil, class: 'control-label' %><br />
		<%= password_field_tag :old_password,nil , class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= label_tag 'Enter new password',nil, class: 'control-label' %><br />
		<%= password_field_tag :new_password,nil , class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= label_tag 'Confirm password',nil, class: 'control-label' %><br />
		<%= password_field_tag :password_confirmation,nil , class: 'form-control' %>
	</div>
	<div class="actions">
		<%= submit_tag 'Change',  class: 'btn btn-default' %>
	</div>
<% end %>
</div>
</div>

app/views/users/forgot_password.html.erb
<h1>Reset password</h1>
<div class="row">
<div class="col-sm-4">
<%= form_tag reset_path do %>
	<div class="form-group">
		<%= label_tag 'Enter your e-mail address',nil, class: 'control-label' %><br />
		<%= text_field_tag :email,nil , class: 'form-control' %>
	</div>
	<div class="actions">
		<%= submit_tag 'Send',  class: 'btn btn-default' %>
	</div>
<% end %>
</div>
</div>

app/views/users/index.html.erb
<h1>noelo</h1>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form' %>