config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tasks
  resource :session, :only => [:new, :create, :destroy]
  get '/login' => "sessions#new", :as => "login"
  get '/logout' => "sessions#destroy", :as => "logout"
  
  get '/forgot_password' => "users#forgot_password", :as => "forgot"
  post 'reset_password' => "users#reset_password", :as => "reset"
  get '/change_password' => "users#change_password", :as => "change_pass"
  post 'commit_change_password' => "users#commit_change_password", :as => "commit_change_pass"
  post 'delete_multiple_tasks' => "tasks#destroy_multiple", :as => "destroy_multiple"

  root 'tasks#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
	  	<div class="jumbotron" style="text-align: center">
	    		<h1>ToDo list</h1>
    			<p>Welcome to task list app!</p>
			<% if logged_in? %>
				<%= link_to "New Task", new_task_path, remote: true, class: "btn btn-primary" %>
			<% end %>
  		</div>
		<% flash.each do |name, msg| %>
			<% if name == "notice" %>
    				<%= content_tag :div, msg, class: "alert alert-info" %>
			<% else %>
				<%= content_tag :div, msg, class: "alert alert-danger" %>
			<% end %>
  		<% end %>
		<br />
		<% if logged_in? %>
			 <div class="dropdown">
  				<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Menu
  				<span class="caret"></span></button>
  				<ul class="dropdown-menu">
    					<li><%= link_to "Change password", change_pass_path %></li>
    					<li><%= link_to link_to 'Delete account', current_user, method: :delete, data: { confirm: 'Are you sure?' } %> </li>
					<li><%= link_to "My tasks", tasks_path %></li>
    					<li><%= link_to "Logout", logout_path %></li>
  				</ul>
			</div>		
		<% end %>
		
	<%= yield %>
	</div>
</body>
</html>